logging:
  # ALL > TRACE > DEBUG > INFO > WARN > ERROR > FATAL > OFF
  level:
    ROOT: INFO
spring:
  flyway:
    enabled: true
    schemas: postable_remittance
    user: ${DB_ADMIN_USERNAME}
    password: ${DB_ADMIN_PASSWORD}
    locations: classpath:db/migration/PostgreSQL
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        generate_statistics: false