create table if not exists patient
(
    id            integer generated by default as identity,
    date_of_birth timestamp(6),
    first_name    varchar(255),
    last_name     varchar(255),
    primary key (id)
);
CREATE INDEX if not exists date_of_birth_idx ON patient (date_of_birth);

create table if not exists payer
(
    id         integer generated by default as identity,
    payer_name varchar(255),
    primary key (id)
);

create table if not exists payer_identity
(
    id                 integer generated by default as identity,
    payer_id           integer,
    payer_identity_val varchar(255),
    primary key (id),
    constraint payer_ident_payer_fk
        foreign key (payer_id) references payer
);

create table if not exists provider
(
    id                 integer generated by default as identity,
    payer_provider_npi varchar(255),
    provider_npi       varchar(255),
    tin                varchar(255),
    primary key (id)
);
--provider indexes
CREATE INDEX tin_idx ON provider (tin);
CREATE INDEX payer_provider_npi_idx ON provider (payer_provider_npi);
CREATE INDEX provider_npi_idx ON provider (provider_npi);

create table if not exists subscriber_patient
(
    id                    integer generated by default as identity,
    patient_id            integer,
    payer_id              integer,
    subscriber_patient_id varchar(255),
    primary key (id),
    constraint subscriber_patient_fk
        foreign key (patient_id) references patient,
    constraint subscriber_payer_fk
        foreign key (payer_id) references payer
);

create table if not exists claim_query
(
    id                    integer generated by default as identity,
    patient_id            integer,
    payer_id              integer,
    provider_id           integer,
    dos_end_dt            timestamp(6),
    dos_start_dt          timestamp(6),
    received_dt           timestamp(6),
    dcn_icn               varchar(255),
    payer_claimid         varchar(255),
    payer_provider_npi    varchar(255),
    provider_claimid      varchar(255),
    provider_npi          varchar(255),
    provider_tin          varchar(255),
    subscriber_patient_id varchar(255),
    primary key (id),
    constraint claim_patient_fk
        foreign key (patient_id) references patient,
    constraint claim_paymt_fk
        foreign key (payer_id) references payer,
    constraint claim_provder_fk
        foreign key (provider_id) references provider
);
CREATE INDEX claim_prov_tin_idx ON claim_query (provider_tin);
CREATE INDEX claim_dates_idx ON claim_query (dos_start_dt, dos_end_dt);
CREATE INDEX claim_subscr_idx ON claim_query (subscriber_patient_id);

create table if not exists payment
(
    amount             integer,
    claim_id           integer,
    id                 integer generated by default as identity,
    payment_dt         timestamp(6),
    payer_identity_val varchar(255),
    payment_number     varchar(255),
    primary key (id),
    constraint paymt_claim_fk
        foreign key (claim_id) references claim_query
);
--payment indexes
CREATE INDEX pmt_search_idx ON payment (amount, payment_number, payment_dt);
CREATE INDEX pmt_ident_val_idx ON payment (payer_identity_val);

create table if not exists remittance
(
    claim_id                    integer,
    id                          integer generated by default as identity,
    remittance_advice_file_size integer,
    remittance_advice_dt        timestamp(6),
    remittance_advice_type      varchar(255),
    remittance_adviceid         varchar(255),
    primary key (id),
    constraint remit_claim_fk
        foreign key (claim_id) references claim_query
);

